name: Run tests

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: ApeWorX/github-action@v1
    - run: ape compile --size
    - run: ape test -s
